name: Enter Reflections

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: all entries made
      run: dos2unix ./.github/workflows/check-complete.sh
